### ISSUE TITLE
Thoughts about adding calc-polyfill?

### ISSUE THREAD

**Issue by corysimmons** [shinnn/lt-ie-9#1]
It's lt ie9 and calc is becoming increasingly important.

**Comment by shinnn** [comment]
I still keep maintaining this project for the current users, but, sorry, I will not add any new features to this project.

Because [Microsoft halted IE < 9 support](http://windows.microsoft.com/en-us/windows/lifecycle) and people all over the world should not use them. That means web developers should show warnings for legacy-browser users instead of adding this library to their websites.

Anyway, thanks for the suggestion, @corysimmons.

**Comment by corysimmons** [comment]
No problem.
