### ISSUE TITLE
Since you're not maintaining anymore...

### ISSUE THREAD

**Issue by corysimmons** [shinnn/lt-ie-9#2]
Would you mind pointing people to https://github.com/corysimmons/ie-love ?

It's essentially the same thing with calc-polyfill added on top.

**Comment by shinnn** [comment]
No thanks. Since [Microsoft halted older IE support](http://windows.microsoft.com/en-us/windows/lifecycle), people all over the world should not use IE < 9 and developers should not include any IE < 9 polyfills like mine and your `ie-love` in their websites.

Also, the biggest reason to reject this proposal is that `ie-love` violates software licenses of [these softwares](https://github.com/shinnn/lt-ie-9#licenses).

**Comment by corysimmons** [comment]
Meh.

**Comment by shinnn** [comment]
Also I'm planning to add a "disrecommendation for IE < 9 polyfill" section to the readme.

**Comment by corysimmons** [comment]
Poor China.
